# Generated by Django 2.2 on 2020-11-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='quiz',
        ),
        migrations.AddField(
            model_name='game',
            name='quiz',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Quiz'),
        ),
    ]
