# Generated by Django 2.2 on 2020-11-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_game_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
