# Generated by Django 2.2 on 2020-11-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201111_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='game_hash',
        ),
    ]
