# Generated by Django 2.2 on 2020-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201114_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quiz_id_check',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
