# Generated by Django 2.2 on 2020-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_game_quiz_id_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
