# Generated by Django 2.2 on 2020-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_game_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='quiz_id_check',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
