# Generated by Django 2.2 on 2020-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201120_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.SlugField(blank=True, max_length=75, null=True),
        ),
    ]
