# Generated by Django 2.2 on 2020-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_game_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(blank=True, choices=[('CR', 'created'), ('S', 'start'), ('C', 'complete')], max_length=2, null=True),
        ),
    ]
