# Generated by Django 2.2 on 2020-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20201122_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_status',
        ),
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='creator_page_visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_page_visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
