# Generated by Django 2.2 on 2020-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201120_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mode',
            field=models.CharField(blank=True, choices=[('J', 'joined'), ('F', 'free')], max_length=1),
        ),
    ]
